# Generated by Django 4.1.7 on 2023-05-08 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_cliente_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='data_publicamento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='curso',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
