# Generated by Django 4.1.7 on 2023-05-08 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_data_publicamento_curso_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='image',
            field=models.ImageField(blank=True, default='defaultcourse.png', null=True, upload_to='curso_image'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='data_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='image',
            field=models.ImageField(blank=True, default='defaultuser.png', null=True, upload_to='profile_image'),
        ),
    ]
