# Generated by Django 4.1.7 on 2023-05-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_curso_image_alter_compra_data_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='user',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Utilizador',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cursos.utilizador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='Utilizador',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cursos.utilizador'),
            preserve_default=False,
        ),
    ]
