# Generated by Django 4.1.7 on 2023-05-11 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_compra_cvv_compra_dat_expir_compra_num_cartao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('area_of_expertise', models.CharField(max_length=100)),
                ('certification', models.FileField(upload_to='certifications/')),
            ],
        ),
        migrations.AlterField(
            model_name='compra',
            name='dat_expir',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 0, 3, 8, 653001, tzinfo=datetime.timezone.utc)),
        ),
    ]
