# Generated by Django 4.1.7 on 2023-05-11 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_application_alter_compra_dat_expir'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='dat_expir',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 3, 1, 57, 445753, tzinfo=datetime.timezone.utc)),
        ),
    ]
