# Generated by Django 4.1.7 on 2023-05-11 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_alter_compra_dat_expir_alter_professor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='dat_expir',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 18, 16, 8, 116973, tzinfo=datetime.timezone.utc)),
        ),
    ]
