# Generated by Django 4.1.7 on 2023-05-11 18:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_remove_curso_professor_alter_compra_dat_expir'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cursos.professor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='dat_expir',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 18, 57, 13, 567967, tzinfo=datetime.timezone.utc)),
        ),
    ]
