# Generated by Django 4.1.7 on 2023-05-11 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_curso_professor_alter_compra_dat_expir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='professor',
        ),
        migrations.AlterField(
            model_name='compra',
            name='dat_expir',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 18, 58, 30, 193856, tzinfo=datetime.timezone.utc)),
        ),
    ]
