# Generated by Django 4.1.7 on 2023-05-11 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_remove_curso_professor_alter_compra_dat_expir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='dat_expir',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 19, 0, 49, 84422, tzinfo=datetime.timezone.utc)),
        ),
    ]
